const FETCH_STARTED = 'FETCH_STARTED';
const FETCH_SUCCESS = 'FETCH_SUCCESS';
const FETCH_FAILURE = 'FETCH_FAILURE';
const CHANGE_FILTER_TEXT = 'CHANGE_FILTER_TEXT';
const CHANGE_IN_STOCK_ONLY = 'CHANGE_IN_STOCK_ONLY';

export {
  FETCH_STARTED,
  FETCH_SUCCESS,
  FETCH_FAILURE,
  CHANGE_FILTER_TEXT,
  CHANGE_IN_STOCK_ONLY,
};
